
title: Ana Campos Portfolio
email: anabcampos199@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Thank you for visiting, let's get in touch!
baseurl: "/project" # the subpath of your site, e.g. /blog
url: "http://anacamposportfolio.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  anacampoos

# Build settings
theme: minima
plugins:
  - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  contacts:
    output: true
  allprojects:
    output: true
